/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_TablePropertiesCollectorFactory */

#ifndef _Included_org_rocksdb_TablePropertiesCollectorFactory
#define _Included_org_rocksdb_TablePropertiesCollectorFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_TablePropertiesCollectorFactory
 * Method:    newCompactOnDeletionCollectorFactory
 * Signature: (JJD)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_TablePropertiesCollectorFactory_newCompactOnDeletionCollectorFactory
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     org_rocksdb_TablePropertiesCollectorFactory
 * Method:    deleteCompactOnDeletionCollectorFactory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_TablePropertiesCollectorFactory_deleteCompactOnDeletionCollectorFactory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
