/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_Logger */

#ifndef _Included_org_rocksdb_Logger
#define _Included_org_rocksdb_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_Logger
 * Method:    newLogger
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_Logger_newLogger
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_Logger
 * Method:    setInfoLogLevel
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_Logger_setInfoLogLevel
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_rocksdb_Logger
 * Method:    infoLogLevel
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_rocksdb_Logger_infoLogLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_Logger
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_Logger_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
