/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_WBWIRocksIterator */

#ifndef _Included_org_rocksdb_WBWIRocksIterator
#define _Included_org_rocksdb_WBWIRocksIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    refresh1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_refresh1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    isValid0Jni
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_WBWIRocksIterator_isValid0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekToFirst0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekToFirst0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekToLast0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekToLast0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    next0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_next0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    prev0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_prev0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    refresh0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_refresh0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seek0Jni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seek0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekForPrev0Jni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekForPrev0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    status0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_status0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekForPrevDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekForPrevDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    seekForPrevByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WBWIRocksIterator_seekForPrevByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_WBWIRocksIterator
 * Method:    entry1
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_rocksdb_WBWIRocksIterator_entry1
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
