/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_util_StdErrLogger */

#ifndef _Included_org_rocksdb_util_StdErrLogger
#define _Included_org_rocksdb_util_StdErrLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_util_StdErrLogger
 * Method:    newStdErrLogger
 * Signature: (BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_util_StdErrLogger_newStdErrLogger
  (JNIEnv *, jclass, jbyte, jstring);

/*
 * Class:     org_rocksdb_util_StdErrLogger
 * Method:    setInfoLogLevel
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_util_StdErrLogger_setInfoLogLevel
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_rocksdb_util_StdErrLogger
 * Method:    infoLogLevel
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_rocksdb_util_StdErrLogger_infoLogLevel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_util_StdErrLogger
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_util_StdErrLogger_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
