/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_SstFileReaderIterator */

#ifndef _Included_org_rocksdb_SstFileReaderIterator
#define _Included_org_rocksdb_SstFileReaderIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    refresh1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_refresh1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    isValid0Jni
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_SstFileReaderIterator_isValid0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekToFirst0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekToFirst0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekToLast0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekToLast0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    next0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_next0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    prev0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_prev0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    refresh0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_refresh0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seek0Jni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seek0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekForPrev0Jni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekForPrev0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    status0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_status0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekForPrevDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekForPrevDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    seekForPrevByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_SstFileReaderIterator_seekForPrevByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    key0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_SstFileReaderIterator_key0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    value0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_SstFileReaderIterator_value0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    keyDirect0
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_SstFileReaderIterator_keyDirect0
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    keyByteArray0
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_SstFileReaderIterator_keyByteArray0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    valueDirect0
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_SstFileReaderIterator_valueDirect0
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_SstFileReaderIterator
 * Method:    valueByteArray0
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_SstFileReaderIterator_valueByteArray0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
