/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_Filter */

#ifndef _Included_org_rocksdb_Filter
#define _Included_org_rocksdb_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_Filter
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_Filter_disposeInternalJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
