/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_HyperClockCache */

#ifndef _Included_org_rocksdb_HyperClockCache
#define _Included_org_rocksdb_HyperClockCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_HyperClockCache
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_HyperClockCache_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_HyperClockCache
 * Method:    newHyperClockCache
 * Signature: (JJIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_HyperClockCache_newHyperClockCache
  (JNIEnv *, jclass, jlong, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
