/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_FlushOptions */

#ifndef _Included_org_rocksdb_FlushOptions
#define _Included_org_rocksdb_FlushOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_FlushOptions
 * Method:    newFlushOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_FlushOptions_newFlushOptions
  (JNIEnv *, jclass);

/*
 * Class:     org_rocksdb_FlushOptions
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_FlushOptions_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_FlushOptions
 * Method:    setWaitForFlush
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_FlushOptions_setWaitForFlush
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_rocksdb_FlushOptions
 * Method:    waitForFlush
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_FlushOptions_waitForFlush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_FlushOptions
 * Method:    setAllowWriteStall
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_FlushOptions_setAllowWriteStall
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_rocksdb_FlushOptions
 * Method:    allowWriteStall
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_FlushOptions_allowWriteStall
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
