/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_RawSstFileReaderIterator */

#ifndef _Included_org_rocksdb_RawSstFileReaderIterator
#define _Included_org_rocksdb_RawSstFileReaderIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_RawSstFileReaderIterator
 * Method:    sequenceNumber
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_RawSstFileReaderIterator_sequenceNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RawSstFileReaderIterator
 * Method:    type
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_rocksdb_RawSstFileReaderIterator_type
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
