/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_RocksIterator */

#ifndef _Included_org_rocksdb_RocksIterator
#define _Included_org_rocksdb_RocksIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    refresh1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_refresh1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    isValid0Jni
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_RocksIterator_isValid0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekToFirst0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekToFirst0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekToLast0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekToLast0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    next0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_next0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    prev0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_prev0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    refresh0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_refresh0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seek0Jni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seek0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekForPrev0Jni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekForPrev0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekForPrevDirect0Jni
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekForPrevDirect0Jni
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    seekForPrevByteArray0Jni
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_seekForPrevByteArray0Jni
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    status0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_RocksIterator_status0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    key0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_RocksIterator_key0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    value0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_RocksIterator_value0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    keyDirect0
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_RocksIterator_keyDirect0
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    keyByteArray0
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_RocksIterator_keyByteArray0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    valueDirect0
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_RocksIterator_valueDirect0
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_rocksdb_RocksIterator
 * Method:    valueByteArray0
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_RocksIterator_valueByteArray0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
