/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_WriteBatchWithIndex */

#ifndef _Included_org_rocksdb_WriteBatchWithIndex
#define _Included_org_rocksdb_WriteBatchWithIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    disposeInternalJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_disposeInternalJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    count0Jni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_rocksdb_WriteBatchWithIndex_count0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    putJni
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_putJni__J_3BI_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    putJni
 * Signature: (J[BI[BIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_putJni__J_3BI_3BIJ
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    putDirectJni
 * Signature: (JLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_putDirectJni
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jint, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    mergeJni
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_mergeJni__J_3BI_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    mergeJni
 * Signature: (J[BI[BIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_mergeJni__J_3BI_3BIJ
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    deleteJni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_deleteJni__J_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    deleteJni
 * Signature: (J[BIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_deleteJni__J_3BIJ
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    singleDeleteJni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_singleDeleteJni__J_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    singleDeleteJni
 * Signature: (J[BIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_singleDeleteJni__J_3BIJ
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    deleteDirectJni
 * Signature: (JLjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_deleteDirectJni
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    deleteRangeJni
 * Signature: (J[BI[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_deleteRangeJni__J_3BI_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    deleteRangeJni
 * Signature: (J[BI[BIJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_deleteRangeJni__J_3BI_3BIJ
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    putLogDataJni
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_putLogDataJni
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    clear0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_clear0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    setSavePoint0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_setSavePoint0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    rollbackToSavePoint0Jni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_rollbackToSavePoint0Jni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    popSavePointJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_popSavePointJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    setMaxBytesJni
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_WriteBatchWithIndex_setMaxBytesJni
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    getWriteBatchJni
 * Signature: (J)Lorg/rocksdb/WriteBatch;
 */
JNIEXPORT jobject JNICALL Java_org_rocksdb_WriteBatchWithIndex_getWriteBatchJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    newWriteBatchWithIndex
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_WriteBatchWithIndex_newWriteBatchWithIndex__
  (JNIEnv *, jclass);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    newWriteBatchWithIndex
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_WriteBatchWithIndex_newWriteBatchWithIndex__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    newWriteBatchWithIndex
 * Signature: (JBIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_WriteBatchWithIndex_newWriteBatchWithIndex__JBIZ
  (JNIEnv *, jclass, jlong, jbyte, jint, jboolean);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    iterator0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_WriteBatchWithIndex_iterator0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    iterator1
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_WriteBatchWithIndex_iterator1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    iteratorWithBase
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_WriteBatchWithIndex_iteratorWithBase
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    getFromBatch
 * Signature: (JJ[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_WriteBatchWithIndex_getFromBatch__JJ_3BI
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    getFromBatch
 * Signature: (JJ[BIJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_WriteBatchWithIndex_getFromBatch__JJ_3BIJ
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jlong);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    getFromBatchAndDB
 * Signature: (JJJ[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_WriteBatchWithIndex_getFromBatchAndDB__JJJ_3BI
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jint);

/*
 * Class:     org_rocksdb_WriteBatchWithIndex
 * Method:    getFromBatchAndDB
 * Signature: (JJJ[BIJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_rocksdb_WriteBatchWithIndex_getFromBatchAndDB__JJJ_3BIJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
